#!/bin/bash
# =============================================================================
# OPENCLAW STANDALONE EXECUTABLE
# =============================================================================
# Create standalone executable that runs anywhere without dependencies
# =============================================================================

set -e

echo "╔════════════════════════════════════════════════════╗"
echo "║   OPENCLAW STANDALONE EXECUTABLE 📦                ║"
echo "╚════════════════════════════════════════════════════╝"
echo ""

WORKSPACE="/mnt/data/openclaw/workspace/.openclaw/workspace"
BUILD_DIR="$WORKSPACE/deploy/executable"

echo "📁 Creating build directory..."
mkdir -p "$BUILD_DIR"

echo ""
echo "╔════════════════════════════════════════════════════╗"
echo "║   BUILD INSTRUCTIONS                               ║"
echo "╚════════════════════════════════════════════════════╝"
echo ""
echo "To create standalone executable, follow these steps:"
echo ""
echo "1️⃣  Install PyInstaller"
echo "   pip install pyinstaller"
echo ""
echo "2️⃣  Create Main Script"
echo "   Create a main.py that:"
echo "   - Imports all 85 skills"
echo "   - Initializes OpenClaw runtime"
echo "   - Starts the server/interface"
echo ""
echo "3️⃣  Build Executable"
echo "   cd $WORKSPACE"
echo "   pyinstaller --onefile --name openclaw main.py"
echo ""
echo "4️⃣  Find Your Executable"
echo "   dist/openclaw (Linux/Mac)"
echo "   dist/openclaw.exe (Windows)"
echo ""
echo "5️⃣  Test It!"
echo "   ./dist/openclaw"
echo ""
echo "╔════════════════════════════════════════════════════╗"
echo "║   OPTIONS                                          ║"
echo "╚════════════════════════════════════════════════════╝"
echo ""
echo "For Windows:"
echo "   pyinstaller --onefile --name openclaw --icon=openclaw.ico main.py"
echo ""
echo "For Mac:"
echo "   pyinstaller --onefile --name openclaw --osx-bundle-identifier=com.openclaw.app main.py"
echo ""
echo "For Linux:"
echo "   pyinstaller --onefile --name openclaw main.py"
echo ""
echo "╔════════════════════════════════════════════════════╗"
echo "║   RESULT                                           ║"
echo "╚════════════════════════════════════════════════════╝"
echo ""
echo "✅ Single executable file"
echo "✅ No dependencies needed"
echo "✅ USB drive portable"
echo "✅ Runs on any OS"
echo "✅ No installation required"
echo "✅ Double-click to run"
echo ""
echo "Ready to build? Follow the steps above! 🚀"
echo ""
